/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated/index"
import { Route as AuthenticatedUsersRouteImport } from "./routes/_authenticated/users"
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated/settings"
import { Route as AuthenticatedResourcesRouteImport } from "./routes/_authenticated/resources"
import { Route as AuthenticatedNotesRouteImport } from "./routes/_authenticated/notes"
import { Route as AuthenticatedMemoriesRouteImport } from "./routes/_authenticated/memories"
import { Route as AuthenticatedJobsRouteImport } from "./routes/_authenticated/jobs"
import { Route as AuthenticatedErrorsRouteImport } from "./routes/_authenticated/errors"
import { Route as AuthenticatedCredentialsRouteImport } from "./routes/_authenticated/credentials"
import { Route as AuthenticatedConversationsRouteImport } from "./routes/_authenticated/conversations"
import { Route as AuthenticatedConsumptionRouteImport } from "./routes/_authenticated/consumption"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: "/resources",
  path: "/resources",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: "/notes",
  path: "/notes",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMemoriesRoute = AuthenticatedMemoriesRouteImport.update({
  id: "/memories",
  path: "/memories",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: "/jobs",
  path: "/jobs",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedErrorsRoute = AuthenticatedErrorsRouteImport.update({
  id: "/errors",
  path: "/errors",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCredentialsRoute =
  AuthenticatedCredentialsRouteImport.update({
    id: "/credentials",
    path: "/credentials",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: "/conversations",
    path: "/conversations",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsumptionRoute =
  AuthenticatedConsumptionRouteImport.update({
    id: "/consumption",
    path: "/consumption",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedIndexRoute
  "/login": typeof LoginRoute
  "/consumption": typeof AuthenticatedConsumptionRoute
  "/conversations": typeof AuthenticatedConversationsRoute
  "/credentials": typeof AuthenticatedCredentialsRoute
  "/errors": typeof AuthenticatedErrorsRoute
  "/jobs": typeof AuthenticatedJobsRoute
  "/memories": typeof AuthenticatedMemoriesRoute
  "/notes": typeof AuthenticatedNotesRoute
  "/resources": typeof AuthenticatedResourcesRoute
  "/settings": typeof AuthenticatedSettingsRoute
  "/users": typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/consumption": typeof AuthenticatedConsumptionRoute
  "/conversations": typeof AuthenticatedConversationsRoute
  "/credentials": typeof AuthenticatedCredentialsRoute
  "/errors": typeof AuthenticatedErrorsRoute
  "/jobs": typeof AuthenticatedJobsRoute
  "/memories": typeof AuthenticatedMemoriesRoute
  "/notes": typeof AuthenticatedNotesRoute
  "/resources": typeof AuthenticatedResourcesRoute
  "/settings": typeof AuthenticatedSettingsRoute
  "/users": typeof AuthenticatedUsersRoute
  "/": typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/login": typeof LoginRoute
  "/_authenticated/consumption": typeof AuthenticatedConsumptionRoute
  "/_authenticated/conversations": typeof AuthenticatedConversationsRoute
  "/_authenticated/credentials": typeof AuthenticatedCredentialsRoute
  "/_authenticated/errors": typeof AuthenticatedErrorsRoute
  "/_authenticated/jobs": typeof AuthenticatedJobsRoute
  "/_authenticated/memories": typeof AuthenticatedMemoriesRoute
  "/_authenticated/notes": typeof AuthenticatedNotesRoute
  "/_authenticated/resources": typeof AuthenticatedResourcesRoute
  "/_authenticated/settings": typeof AuthenticatedSettingsRoute
  "/_authenticated/users": typeof AuthenticatedUsersRoute
  "/_authenticated/": typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/consumption"
    | "/conversations"
    | "/credentials"
    | "/errors"
    | "/jobs"
    | "/memories"
    | "/notes"
    | "/resources"
    | "/settings"
    | "/users"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/consumption"
    | "/conversations"
    | "/credentials"
    | "/errors"
    | "/jobs"
    | "/memories"
    | "/notes"
    | "/resources"
    | "/settings"
    | "/users"
    | "/"
  id:
    | "__root__"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/consumption"
    | "/_authenticated/conversations"
    | "/_authenticated/credentials"
    | "/_authenticated/errors"
    | "/_authenticated/jobs"
    | "/_authenticated/memories"
    | "/_authenticated/notes"
    | "/_authenticated/resources"
    | "/_authenticated/settings"
    | "/_authenticated/users"
    | "/_authenticated/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/": {
      id: "/_authenticated/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/users": {
      id: "/_authenticated/users"
      path: "/users"
      fullPath: "/users"
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/settings": {
      id: "/_authenticated/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/resources": {
      id: "/_authenticated/resources"
      path: "/resources"
      fullPath: "/resources"
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/notes": {
      id: "/_authenticated/notes"
      path: "/notes"
      fullPath: "/notes"
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/memories": {
      id: "/_authenticated/memories"
      path: "/memories"
      fullPath: "/memories"
      preLoaderRoute: typeof AuthenticatedMemoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/jobs": {
      id: "/_authenticated/jobs"
      path: "/jobs"
      fullPath: "/jobs"
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/errors": {
      id: "/_authenticated/errors"
      path: "/errors"
      fullPath: "/errors"
      preLoaderRoute: typeof AuthenticatedErrorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/credentials": {
      id: "/_authenticated/credentials"
      path: "/credentials"
      fullPath: "/credentials"
      preLoaderRoute: typeof AuthenticatedCredentialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/conversations": {
      id: "/_authenticated/conversations"
      path: "/conversations"
      fullPath: "/conversations"
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/consumption": {
      id: "/_authenticated/consumption"
      path: "/consumption"
      fullPath: "/consumption"
      preLoaderRoute: typeof AuthenticatedConsumptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConsumptionRoute: typeof AuthenticatedConsumptionRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedCredentialsRoute: typeof AuthenticatedCredentialsRoute
  AuthenticatedErrorsRoute: typeof AuthenticatedErrorsRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedMemoriesRoute: typeof AuthenticatedMemoriesRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConsumptionRoute: AuthenticatedConsumptionRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedCredentialsRoute: AuthenticatedCredentialsRoute,
  AuthenticatedErrorsRoute: AuthenticatedErrorsRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedMemoriesRoute: AuthenticatedMemoriesRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
