/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as UnauthorizedRouteImport } from "./routes/unauthorized"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as UsersIndexRouteImport } from "./routes/users/index"
import { Route as SettingsIndexRouteImport } from "./routes/settings/index"
import { Route as ResourcesIndexRouteImport } from "./routes/resources/index"
import { Route as NotesIndexRouteImport } from "./routes/notes/index"
import { Route as MemoriesIndexRouteImport } from "./routes/memories/index"
import { Route as JobsIndexRouteImport } from "./routes/jobs/index"
import { Route as ErrorsIndexRouteImport } from "./routes/errors/index"
import { Route as CredentialsIndexRouteImport } from "./routes/credentials/index"
import { Route as ConversationsIndexRouteImport } from "./routes/conversations/index"
import { Route as ConsumptionIndexRouteImport } from "./routes/consumption/index"
import { Route as UsersSlackUserIdRouteImport } from "./routes/users/$slackUserId"
import { Route as ResourcesIdRouteImport } from "./routes/resources/$id"
import { Route as NotesIdRouteImport } from "./routes/notes/$id"
import { Route as MemoriesEntitiesRouteImport } from "./routes/memories/entities"
import { Route as MemoriesIdRouteImport } from "./routes/memories/$id"
import { Route as JobsIdRouteImport } from "./routes/jobs/$id"
import { Route as ErrorsIdRouteImport } from "./routes/errors/$id"
import { Route as CredentialsIdRouteImport } from "./routes/credentials/$id"
import { Route as ConversationsInvocationsRouteImport } from "./routes/conversations/invocations"
import { Route as ConversationsIdRouteImport } from "./routes/conversations/$id"
import { Route as ConversationsThreadsChannelIdThreadTsRouteImport } from "./routes/conversations/threads.$channelId.$threadTs"

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: "/unauthorized",
  path: "/unauthorized",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: "/resources/",
  path: "/resources/",
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: "/notes/",
  path: "/notes/",
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: "/memories/",
  path: "/memories/",
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: "/jobs/",
  path: "/jobs/",
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsIndexRoute = ErrorsIndexRouteImport.update({
  id: "/errors/",
  path: "/errors/",
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsIndexRoute = CredentialsIndexRouteImport.update({
  id: "/credentials/",
  path: "/credentials/",
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: "/conversations/",
  path: "/conversations/",
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumptionIndexRoute = ConsumptionIndexRouteImport.update({
  id: "/consumption/",
  path: "/consumption/",
  getParentRoute: () => rootRouteImport,
} as any)
const UsersSlackUserIdRoute = UsersSlackUserIdRouteImport.update({
  id: "/users/$slackUserId",
  path: "/users/$slackUserId",
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIdRoute = ResourcesIdRouteImport.update({
  id: "/resources/$id",
  path: "/resources/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: "/notes/$id",
  path: "/notes/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesEntitiesRoute = MemoriesEntitiesRouteImport.update({
  id: "/memories/entities",
  path: "/memories/entities",
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIdRoute = MemoriesIdRouteImport.update({
  id: "/memories/$id",
  path: "/memories/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: "/jobs/$id",
  path: "/jobs/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsIdRoute = ErrorsIdRouteImport.update({
  id: "/errors/$id",
  path: "/errors/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsIdRoute = CredentialsIdRouteImport.update({
  id: "/credentials/$id",
  path: "/credentials/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsInvocationsRoute =
  ConversationsInvocationsRouteImport.update({
    id: "/conversations/invocations",
    path: "/conversations/invocations",
    getParentRoute: () => rootRouteImport,
  } as any)
const ConversationsIdRoute = ConversationsIdRouteImport.update({
  id: "/conversations/$id",
  path: "/conversations/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsThreadsChannelIdThreadTsRoute =
  ConversationsThreadsChannelIdThreadTsRouteImport.update({
    id: "/conversations/threads/$channelId/$threadTs",
    path: "/conversations/threads/$channelId/$threadTs",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/conversations/$id": typeof ConversationsIdRoute
  "/conversations/invocations": typeof ConversationsInvocationsRoute
  "/credentials/$id": typeof CredentialsIdRoute
  "/errors/$id": typeof ErrorsIdRoute
  "/jobs/$id": typeof JobsIdRoute
  "/memories/$id": typeof MemoriesIdRoute
  "/memories/entities": typeof MemoriesEntitiesRoute
  "/notes/$id": typeof NotesIdRoute
  "/resources/$id": typeof ResourcesIdRoute
  "/users/$slackUserId": typeof UsersSlackUserIdRoute
  "/consumption/": typeof ConsumptionIndexRoute
  "/conversations/": typeof ConversationsIndexRoute
  "/credentials/": typeof CredentialsIndexRoute
  "/errors/": typeof ErrorsIndexRoute
  "/jobs/": typeof JobsIndexRoute
  "/memories/": typeof MemoriesIndexRoute
  "/notes/": typeof NotesIndexRoute
  "/resources/": typeof ResourcesIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/users/": typeof UsersIndexRoute
  "/conversations/threads/$channelId/$threadTs": typeof ConversationsThreadsChannelIdThreadTsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/conversations/$id": typeof ConversationsIdRoute
  "/conversations/invocations": typeof ConversationsInvocationsRoute
  "/credentials/$id": typeof CredentialsIdRoute
  "/errors/$id": typeof ErrorsIdRoute
  "/jobs/$id": typeof JobsIdRoute
  "/memories/$id": typeof MemoriesIdRoute
  "/memories/entities": typeof MemoriesEntitiesRoute
  "/notes/$id": typeof NotesIdRoute
  "/resources/$id": typeof ResourcesIdRoute
  "/users/$slackUserId": typeof UsersSlackUserIdRoute
  "/consumption": typeof ConsumptionIndexRoute
  "/conversations": typeof ConversationsIndexRoute
  "/credentials": typeof CredentialsIndexRoute
  "/errors": typeof ErrorsIndexRoute
  "/jobs": typeof JobsIndexRoute
  "/memories": typeof MemoriesIndexRoute
  "/notes": typeof NotesIndexRoute
  "/resources": typeof ResourcesIndexRoute
  "/settings": typeof SettingsIndexRoute
  "/users": typeof UsersIndexRoute
  "/conversations/threads/$channelId/$threadTs": typeof ConversationsThreadsChannelIdThreadTsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/conversations/$id": typeof ConversationsIdRoute
  "/conversations/invocations": typeof ConversationsInvocationsRoute
  "/credentials/$id": typeof CredentialsIdRoute
  "/errors/$id": typeof ErrorsIdRoute
  "/jobs/$id": typeof JobsIdRoute
  "/memories/$id": typeof MemoriesIdRoute
  "/memories/entities": typeof MemoriesEntitiesRoute
  "/notes/$id": typeof NotesIdRoute
  "/resources/$id": typeof ResourcesIdRoute
  "/users/$slackUserId": typeof UsersSlackUserIdRoute
  "/consumption/": typeof ConsumptionIndexRoute
  "/conversations/": typeof ConversationsIndexRoute
  "/credentials/": typeof CredentialsIndexRoute
  "/errors/": typeof ErrorsIndexRoute
  "/jobs/": typeof JobsIndexRoute
  "/memories/": typeof MemoriesIndexRoute
  "/notes/": typeof NotesIndexRoute
  "/resources/": typeof ResourcesIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/users/": typeof UsersIndexRoute
  "/conversations/threads/$channelId/$threadTs": typeof ConversationsThreadsChannelIdThreadTsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/unauthorized"
    | "/conversations/$id"
    | "/conversations/invocations"
    | "/credentials/$id"
    | "/errors/$id"
    | "/jobs/$id"
    | "/memories/$id"
    | "/memories/entities"
    | "/notes/$id"
    | "/resources/$id"
    | "/users/$slackUserId"
    | "/consumption/"
    | "/conversations/"
    | "/credentials/"
    | "/errors/"
    | "/jobs/"
    | "/memories/"
    | "/notes/"
    | "/resources/"
    | "/settings/"
    | "/users/"
    | "/conversations/threads/$channelId/$threadTs"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/unauthorized"
    | "/conversations/$id"
    | "/conversations/invocations"
    | "/credentials/$id"
    | "/errors/$id"
    | "/jobs/$id"
    | "/memories/$id"
    | "/memories/entities"
    | "/notes/$id"
    | "/resources/$id"
    | "/users/$slackUserId"
    | "/consumption"
    | "/conversations"
    | "/credentials"
    | "/errors"
    | "/jobs"
    | "/memories"
    | "/notes"
    | "/resources"
    | "/settings"
    | "/users"
    | "/conversations/threads/$channelId/$threadTs"
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/unauthorized"
    | "/conversations/$id"
    | "/conversations/invocations"
    | "/credentials/$id"
    | "/errors/$id"
    | "/jobs/$id"
    | "/memories/$id"
    | "/memories/entities"
    | "/notes/$id"
    | "/resources/$id"
    | "/users/$slackUserId"
    | "/consumption/"
    | "/conversations/"
    | "/credentials/"
    | "/errors/"
    | "/jobs/"
    | "/memories/"
    | "/notes/"
    | "/resources/"
    | "/settings/"
    | "/users/"
    | "/conversations/threads/$channelId/$threadTs"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ConversationsIdRoute: typeof ConversationsIdRoute
  ConversationsInvocationsRoute: typeof ConversationsInvocationsRoute
  CredentialsIdRoute: typeof CredentialsIdRoute
  ErrorsIdRoute: typeof ErrorsIdRoute
  JobsIdRoute: typeof JobsIdRoute
  MemoriesIdRoute: typeof MemoriesIdRoute
  MemoriesEntitiesRoute: typeof MemoriesEntitiesRoute
  NotesIdRoute: typeof NotesIdRoute
  ResourcesIdRoute: typeof ResourcesIdRoute
  UsersSlackUserIdRoute: typeof UsersSlackUserIdRoute
  ConsumptionIndexRoute: typeof ConsumptionIndexRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
  CredentialsIndexRoute: typeof CredentialsIndexRoute
  ErrorsIndexRoute: typeof ErrorsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ConversationsThreadsChannelIdThreadTsRoute: typeof ConversationsThreadsChannelIdThreadTsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/unauthorized": {
      id: "/unauthorized"
      path: "/unauthorized"
      fullPath: "/unauthorized"
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/users/": {
      id: "/users/"
      path: "/users"
      fullPath: "/users/"
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/": {
      id: "/settings/"
      path: "/settings"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/resources/": {
      id: "/resources/"
      path: "/resources"
      fullPath: "/resources/"
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/notes/": {
      id: "/notes/"
      path: "/notes"
      fullPath: "/notes/"
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/memories/": {
      id: "/memories/"
      path: "/memories"
      fullPath: "/memories/"
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/jobs/": {
      id: "/jobs/"
      path: "/jobs"
      fullPath: "/jobs/"
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/errors/": {
      id: "/errors/"
      path: "/errors"
      fullPath: "/errors/"
      preLoaderRoute: typeof ErrorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/credentials/": {
      id: "/credentials/"
      path: "/credentials"
      fullPath: "/credentials/"
      preLoaderRoute: typeof CredentialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/conversations/": {
      id: "/conversations/"
      path: "/conversations"
      fullPath: "/conversations/"
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/consumption/": {
      id: "/consumption/"
      path: "/consumption"
      fullPath: "/consumption/"
      preLoaderRoute: typeof ConsumptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/users/$slackUserId": {
      id: "/users/$slackUserId"
      path: "/users/$slackUserId"
      fullPath: "/users/$slackUserId"
      preLoaderRoute: typeof UsersSlackUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/resources/$id": {
      id: "/resources/$id"
      path: "/resources/$id"
      fullPath: "/resources/$id"
      preLoaderRoute: typeof ResourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/notes/$id": {
      id: "/notes/$id"
      path: "/notes/$id"
      fullPath: "/notes/$id"
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/memories/entities": {
      id: "/memories/entities"
      path: "/memories/entities"
      fullPath: "/memories/entities"
      preLoaderRoute: typeof MemoriesEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/memories/$id": {
      id: "/memories/$id"
      path: "/memories/$id"
      fullPath: "/memories/$id"
      preLoaderRoute: typeof MemoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/jobs/$id": {
      id: "/jobs/$id"
      path: "/jobs/$id"
      fullPath: "/jobs/$id"
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/errors/$id": {
      id: "/errors/$id"
      path: "/errors/$id"
      fullPath: "/errors/$id"
      preLoaderRoute: typeof ErrorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/credentials/$id": {
      id: "/credentials/$id"
      path: "/credentials/$id"
      fullPath: "/credentials/$id"
      preLoaderRoute: typeof CredentialsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/conversations/invocations": {
      id: "/conversations/invocations"
      path: "/conversations/invocations"
      fullPath: "/conversations/invocations"
      preLoaderRoute: typeof ConversationsInvocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/conversations/$id": {
      id: "/conversations/$id"
      path: "/conversations/$id"
      fullPath: "/conversations/$id"
      preLoaderRoute: typeof ConversationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/conversations/threads/$channelId/$threadTs": {
      id: "/conversations/threads/$channelId/$threadTs"
      path: "/conversations/threads/$channelId/$threadTs"
      fullPath: "/conversations/threads/$channelId/$threadTs"
      preLoaderRoute: typeof ConversationsThreadsChannelIdThreadTsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ConversationsIdRoute: ConversationsIdRoute,
  ConversationsInvocationsRoute: ConversationsInvocationsRoute,
  CredentialsIdRoute: CredentialsIdRoute,
  ErrorsIdRoute: ErrorsIdRoute,
  JobsIdRoute: JobsIdRoute,
  MemoriesIdRoute: MemoriesIdRoute,
  MemoriesEntitiesRoute: MemoriesEntitiesRoute,
  NotesIdRoute: NotesIdRoute,
  ResourcesIdRoute: ResourcesIdRoute,
  UsersSlackUserIdRoute: UsersSlackUserIdRoute,
  ConsumptionIndexRoute: ConsumptionIndexRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
  CredentialsIndexRoute: CredentialsIndexRoute,
  ErrorsIndexRoute: ErrorsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ConversationsThreadsChannelIdThreadTsRoute:
    ConversationsThreadsChannelIdThreadTsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
